# Generated by Django 4.2.3 on 2023-07-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alergias', models.TextField()),
                ('medicamentos_em_uso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('especialidade', models.CharField(choices=[('1', 'Cardiologia'), ('2', 'Dermatologia'), ('3', 'Neurologia'), ('4', 'Psiquiatria'), ('5', 'Psicologia'), ('6', 'Odontologia'), ('7', 'Fisioterapia'), ('8', 'Pediatria')], default='1', max_length=1)),
                ('pacientes', models.ManyToManyField(related_name='clinicas_internacao', to='clinica.paciente')),
            ],
        ),
    ]
